import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
export const unitRunStatus = pgEnum("unit_run_status", ["in_progress", "completed", "abandoned", "expired"]);
export const masteryDimension = pgEnum("mastery_dimension", ["reading_recognition", "listening_recognition", "active_recall"]);
const audit = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() };
export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), displayName: text("display_name").notNull(), ...audit });
export const languages = pgTable("languages", { id: uuid("id").primaryKey().defaultRandom(), tag: text("tag").notNull().unique(), displayName: text("display_name").notNull(), ...audit });
export const learningPaths = pgTable("learning_paths", { id: uuid("id").primaryKey().defaultRandom(), slug: text("slug").notNull().unique(), title: text("title").notNull(), targetLanguageId: uuid("target_language_id").notNull().references(() => languages.id), supportLanguageId: uuid("support_language_id").notNull().references(() => languages.id), ...audit });
export const userLearningPaths = pgTable("user_learning_paths", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id), learningPathId: uuid("learning_path_id").notNull().references(() => learningPaths.id), dailyGoalMinutes: integer("daily_goal_minutes").notNull().default(10), ...audit }, (t) => [uniqueIndex("user_learning_path_unique").on(t.userId, t.learningPathId)]);
export const courses = pgTable("courses", { id: uuid("id").primaryKey().defaultRandom(), learningPathId: uuid("learning_path_id").notNull().references(() => learningPaths.id), slug: text("slug").notNull(), title: text("title").notNull(), ...audit }, (t) => [uniqueIndex("course_path_slug_unique").on(t.learningPathId, t.slug)]);
export const courseVersions = pgTable("course_versions", { id: uuid("id").primaryKey().defaultRandom(), courseId: uuid("course_id").notNull().references(() => courses.id), version: integer("version").notNull(), status: text("status").notNull().default("published"), ...audit }, (t) => [uniqueIndex("course_version_unique").on(t.courseId, t.version)]);
export const learningUnits = pgTable("learning_units", { id: uuid("id").primaryKey().defaultRandom(), courseVersionId: uuid("course_version_id").notNull().references(() => courseVersions.id), position: integer("position").notNull(), title: text("title").notNull(), estimatedSeconds: integer("estimated_seconds").notNull(), ...audit });
export const exercises = pgTable("exercises", { id: uuid("id").primaryKey().defaultRandom(), learningUnitId: uuid("learning_unit_id").notNull().references(() => learningUnits.id), position: integer("position").notNull(), type: text("type").notNull(), prompt: text("prompt").notNull(), content: jsonb("content").$type<Record<string, unknown>>().notNull(), answer: jsonb("answer").$type<Record<string, unknown>>().notNull(), feedback: jsonb("feedback").$type<Record<string, unknown>>().notNull(), ...audit });
export const unitRuns = pgTable("unit_runs", { id: uuid("id").primaryKey().defaultRandom(), userLearningPathId: uuid("user_learning_path_id").notNull().references(() => userLearningPaths.id), learningUnitId: uuid("learning_unit_id").notNull().references(() => learningUnits.id), status: unitRunStatus("status").notNull().default("in_progress"), shuffleSeed: integer("shuffle_seed").notNull(), currentPosition: integer("current_position").notNull().default(0), completedAt: timestamp("completed_at", { withTimezone: true }), ...audit }, (t) => [index("unit_runs_resume_idx").on(t.userLearningPathId, t.status, t.createdAt)]);
export const exerciseAttempts = pgTable("exercise_attempts", { id: uuid("id").primaryKey().defaultRandom(), unitRunId: uuid("unit_run_id").notNull().references(() => unitRuns.id), exerciseId: uuid("exercise_id").notNull().references(() => exercises.id), clientEventId: uuid("client_event_id").notNull(), response: jsonb("response").$type<Record<string, unknown>>().notNull(), displayOrder: jsonb("display_order").$type<string[]>().notNull(), isCorrect: boolean("is_correct").notNull(), ...audit }, (t) => [uniqueIndex("attempt_client_event_unique").on(t.unitRunId, t.clientEventId)]);
export const masteryStates = pgTable("mastery_states", { id: uuid("id").primaryKey().defaultRandom(), userLearningPathId: uuid("user_learning_path_id").notNull().references(() => userLearningPaths.id), key: text("key").notNull(), dimension: masteryDimension("dimension").notNull(), intervalDays: integer("interval_days").notNull().default(0), nextReviewAt: timestamp("next_review_at", { withTimezone: true }), ...audit }, (t) => [uniqueIndex("mastery_unique").on(t.userLearningPathId, t.key, t.dimension)]);

