import { db } from "@/db/client";
import { learningPaths,lexemes,lexemeSenses,senseTranslations,userLearningPaths,userVocabulary,vocabularyExamples,vocabularyInjectionTasks } from "@/db/schema";
import { requireUserId } from "@/lib/dev-auth";
import { normalizeVocabulary } from "@/lib/vocabulary";
import { and,eq } from "drizzle-orm";
import { z } from "zod";

const draftSchema=z.object({schemaVersion:z.literal(1),canonicalForm:z.string().trim().min(1).max(200),lexemeType:z.enum(["word","phrase"]),partOfSpeech:z.string().trim().max(50).optional(),definition:z.string().trim().min(1).max(1000),register:z.string().trim().min(1).max(50).default("neutral"),domain:z.string().trim().min(1).max(100).default("general_business"),translation:z.string().trim().min(1).max(500),usageNote:z.string().trim().max(1000).optional(),example:z.string().trim().min(1).max(1000),exampleTranslation:z.string().trim().max(1000).optional(),source:z.object({type:z.enum(["project_authored","dictionary","user_context","licensed_dataset"]),identifier:z.string().trim().max(500).optional(),license:z.string().trim().max(200).optional()})});
const actionSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("save_draft"),draft:draftSchema}),
 z.object({action:z.literal("approve"),confirm:z.literal(true)}),
 z.object({action:z.literal("reject"),reason:z.string().trim().min(1).max(500)}),
]);
async function ownedTask(id:string,userId:string){return (await db.select({task:vocabularyInjectionTasks,pathId:userLearningPaths.id,targetLanguageId:learningPaths.targetLanguageId,supportLanguageId:learningPaths.supportLanguageId}).from(vocabularyInjectionTasks).innerJoin(userLearningPaths,eq(vocabularyInjectionTasks.userLearningPathId,userLearningPaths.id)).innerJoin(learningPaths,eq(userLearningPaths.learningPathId,learningPaths.id)).where(and(eq(vocabularyInjectionTasks.id,id),eq(userLearningPaths.userId,userId))).limit(1))[0]}
export async function GET(_:Request,context:{params:Promise<{id:string}>}){const{id}=await context.params;const owned=await ownedTask(id,requireUserId());if(!owned)return Response.json({error:"Not found"},{status:404});return Response.json({schemaVersion:1,task:{id:owned.task.id,rawText:owned.task.rawText,normalizedText:owned.task.normalizedText,status:owned.task.status},draft:owned.task.aiDraft??null})}
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const parsed=actionSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid review action"},{status:400});const{id}=await context.params;const owned=await ownedTask(id,requireUserId());if(!owned)return Response.json({error:"Not found"},{status:404});const action=parsed.data;
 if(action.action==="save_draft"){if(!["captured","needs_enrichment","needs_review"].includes(owned.task.status))return Response.json({error:"Task cannot accept a draft"},{status:409});await db.update(vocabularyInjectionTasks).set({aiSchemaVersion:1,aiDraft:action.draft,status:"needs_review"}).where(eq(vocabularyInjectionTasks.id,id));return Response.json({status:"needs_review",draft:action.draft})}
 if(action.action==="reject"){if(owned.task.status!=="needs_review")return Response.json({error:"Only a reviewable draft can be rejected"},{status:409});await db.update(vocabularyInjectionTasks).set({status:"rejected",rejectionReason:action.reason,reviewedAt:new Date()}).where(eq(vocabularyInjectionTasks.id,id));return Response.json({status:"rejected"})}
 if(owned.task.status!=="needs_review"||owned.task.aiSchemaVersion!==1)return Response.json({error:"A validated draft must be reviewed first"},{status:409});const draft=draftSchema.parse(owned.task.aiDraft);const normalized=normalizeVocabulary(draft.canonicalForm);const result=await db.transaction(async tx=>{let[lexeme]=await tx.select().from(lexemes).where(and(eq(lexemes.languageId,owned.targetLanguageId),eq(lexemes.normalizedForm,normalized))).limit(1);if(!lexeme){[lexeme]=await tx.insert(lexemes).values({languageId:owned.targetLanguageId,canonicalForm:draft.canonicalForm,normalizedForm:normalized,type:draft.lexemeType,metadata:{source:draft.source}}).returning()}let[sense]=await tx.select().from(lexemeSenses).where(and(eq(lexemeSenses.lexemeId,lexeme.id),eq(lexemeSenses.definition,draft.definition))).limit(1);if(!sense){[sense]=await tx.insert(lexemeSenses).values({lexemeId:lexeme.id,partOfSpeech:draft.partOfSpeech,definitionLanguageId:owned.targetLanguageId,definition:draft.definition,register:draft.register,domain:draft.domain,status:"approved",source:draft.source}).returning()}await tx.insert(senseTranslations).values({lexemeSenseId:sense.id,languageId:owned.supportLanguageId,translation:draft.translation,usageNote:draft.usageNote,status:"approved"}).onConflictDoNothing();await tx.insert(vocabularyExamples).values({lexemeSenseId:sense.id,textLanguageId:owned.targetLanguageId,text:draft.example,translationLanguageId:owned.supportLanguageId,translation:draft.exampleTranslation,status:"approved",source:draft.source}).onConflictDoNothing();const[vocabulary]=await tx.insert(userVocabulary).values({userLearningPathId:owned.pathId,lexemeSenseId:sense.id,status:"ready_to_learn"}).onConflictDoUpdate({target:[userVocabulary.userLearningPathId,userVocabulary.lexemeSenseId],set:{status:"ready_to_learn"}}).returning();await tx.update(vocabularyInjectionTasks).set({status:"ready_to_learn",matchedLexemeSenseId:sense.id,reviewedAt:new Date()}).where(eq(vocabularyInjectionTasks.id,id));return{lexemeId:lexeme.id,senseId:sense.id,userVocabularyId:vocabulary.id}});return Response.json({status:"ready_to_learn",...result})}
