"use client";
import { useEffect,useRef,useState } from "react";
type Asset={id:string;status:string;url:string|null;voice:string|null;durationMs:number|null};
export function AudioPlayer({exerciseId,text,asset}:{exerciseId:string;text:string;asset?:Asset}){const[playing,setPlaying]=useState(false),[rate,setRate]=useState<"0.85"|"1.0">("0.85"),[captions,setCaptions]=useState(false),[error,setError]=useState("");const audioRef=useRef<HTMLAudioElement|null>(null);
 function record(eventType:"play"|"pause"|"replay"|"complete"|"unfamiliar"|"error",metadata:Record<string,unknown>={}){void fetch("/api/audio-events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientEventId:crypto.randomUUID(),audioAssetId:asset?.id,exerciseId,eventType,playbackRate:rate,metadata:{fallback:!asset?.url,...metadata}})})}
 function stop(){audioRef.current?.pause();if("speechSynthesis"in window)window.speechSynthesis.cancel();setPlaying(false)}
 function play(replay=false){window.dispatchEvent(new CustomEvent("lalea:audio-start",{detail:exerciseId}));setError("");if(asset?.url){if(!audioRef.current){const audio=new Audio(asset.url);audio.onended=()=>{setPlaying(false);record("complete")};audio.onerror=()=>{setError("固定音訊載入失敗，已切換瀏覽器語音備援。");record("error",{reason:"asset_load_failed"});audioRef.current=null;playSpeech()};audioRef.current=audio}audioRef.current.currentTime=replay?0:audioRef.current.currentTime;audioRef.current.playbackRate=Number(rate);void audioRef.current.play();setPlaying(true)}else playSpeech();record(replay?"replay":"play")}
 function playSpeech(){if(!("speechSynthesis"in window)){setError("此瀏覽器無法播放語音。");record("error",{reason:"speech_unavailable"});return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="en-US";utterance.rate=Number(rate);utterance.onend=()=>{setPlaying(false);record("complete")};utterance.onerror=()=>{setPlaying(false);setError("語音播放失敗，請稍後重試。");record("error",{reason:"speech_failed"})};window.speechSynthesis.speak(utterance);setPlaying(true)}
 useEffect(()=>{const listener=(event:Event)=>{if((event as CustomEvent<string>).detail!==exerciseId)stop()};window.addEventListener("lalea:audio-start",listener);return()=>{window.removeEventListener("lalea:audio-start",listener);stop()}},[exerciseId]);
 return <div><div className="audio"><button onClick={()=>playing?(stop(),record("pause")):play()} aria-label={playing?"暫停英文":"播放英文"}>{playing?"Ⅱ":"▶"}</button><div><strong>{asset?.status==="approved"?"固定教材音訊":"瀏覽器語音備援"}</strong><br/><small>{rate}× · 可重複播放</small></div></div><div className="audio-controls"><button onClick={()=>play(true)}>重播</button><button onClick={()=>setRate(value=>value==="0.85"?"1.0":"0.85")}>速度 {rate}×</button><button onClick={()=>setCaptions(value=>!value)}>{captions?"隱藏字幕":"顯示字幕"}</button><button onClick={()=>{record("unfamiliar");setError("已標記不熟，會提早安排正式複習；不會記成答錯。")}}>不熟</button></div>{captions&&<p className="context">{text}</p>}{error&&<p className="error" role="status">{error}</p>}</div>}
