"use client";
import { useEffect, useMemo, useState } from "react";
type Option={id:string;text:string}; type Exercise={id:string;position:number;type:string;prompt:string;content:{context?:string;speech?:string;options?:Option[]}};
type Run={id:string;currentPosition:number;status:string;exercises:Exercise[]}; type Feedback={isCorrect:boolean;correctIds:string[];message:string};
export function LearningApp(){
 const[screen,setScreen]=useState<"home"|"lesson"|"done">("home"),[minutes,setMinutes]=useState(5),[mode,setMode]=useState("一般");
 const[run,setRun]=useState<Run|null>(null),[index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>([]),[feedback,setFeedback]=useState<Feedback|null>(null);
 const[busy,setBusy]=useState(false),[error,setError]=useState(""),[correct,setCorrect]=useState(0); const exercise=run?.exercises[index];
 const optionMap=useMemo(()=>new Map(exercise?.content.options?.map(o=>[o.id,o.text])??[]),[exercise]);
 async function start(){setBusy(true);setError("");try{const created=await fetch("/api/unit-runs",{method:"POST"});if(!created.ok)throw new Error("目前無法開始課程，請確認資料庫已啟動。");const{id}=await created.json();const response=await fetch(`/api/unit-runs/${id}`);if(!response.ok)throw new Error("無法載入課程內容。");const data:Run=await response.json();setRun(data);setIndex(Math.min(Math.max(data.currentPosition,0),Math.max(data.exercises.length-1,0)));setSelected([]);setFeedback(null);setScreen("lesson")}catch(cause){setError(cause instanceof Error?cause.message:"發生未預期錯誤。")}finally{setBusy(false)}}
 function choose(id:string){if(feedback)return;if(exercise?.type==="chunk_ordering")setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);else setSelected([id])}
 function speak(){if(!exercise?.content.speech||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(exercise.content.speech);u.lang="en-US";u.rate=.85;window.speechSynthesis.speak(u)}
 async function submit(){if(!run||!exercise||!selected.length)return;setBusy(true);setError("");try{const response=await fetch("/api/exercise-attempts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({unitRunId:run.id,exerciseId:exercise.id,clientEventId:crypto.randomUUID(),selectedIds:selected,displayOrder:exercise.content.options?.map(o=>o.id)??[]})});if(!response.ok)throw new Error("答案送出失敗，請再試一次。");const result:Feedback=await response.json();setFeedback(result);if(result.isCorrect)setCorrect(v=>v+1)}catch(cause){setError(cause instanceof Error?cause.message:"答案送出失敗。")}finally{setBusy(false)}}
 async function next(){if(!run||!feedback)return;if(index<run.exercises.length-1){setIndex(v=>v+1);setSelected([]);setFeedback(null);return}setBusy(true);const response=await fetch(`/api/unit-runs/${run.id}/complete`,{method:"POST"});setBusy(false);if(response.ok)setScreen("done");else setError("課程完成狀態未能儲存，請再試一次。")}
 useEffect(()=>()=>{if("speechSynthesis"in window)window.speechSynthesis.cancel()},[]);
 if(screen==="home")return <main className="shell"><header className="brand"><strong>LaLea</strong><span>Language Learning</span></header><p className="eyebrow">今天的小步前進</p><h1>用零散時間，練出能開口的職場英文。</h1><p className="lead">先從一般商務溝通開始。每堂短課會混合單字、片語、聽力和實際對話。</p><section className="card"><span className="label">現在有多少時間？</span><div className="pills">{[3,5,10].map(v=><button className="pill" aria-pressed={minutes===v} onClick={()=>setMinutes(v)} key={v}>{v} 分鐘</button>)}</div></section><section className="card"><span className="label">目前的環境</span><div className="pills">{["一般","安靜","純聽"].map(v=><button className="pill" aria-pressed={mode===v} onClick={()=>setMode(v)} key={v}>{v}</button>)}</div></section>{error&&<p className="error" role="alert">{error}</p>}<button className="primary resume" onClick={start} disabled={busy}>{busy?"準備課程中…":`繼續學習 · ${minutes} 分鐘`}</button></main>;
 if(screen==="done")return <main className="shell finish"><div className="mark">✓</div><p className="eyebrow">今日短課完成</p><h1>做得好，這些句子已加入你的學習進度。</h1><div className="stats"><div className="stat"><strong>{correct}/{run?.exercises.length}</strong><span>答對</span></div><div className="stat"><strong>3</strong><span>片語</span></div><div className="stat"><strong>約 {minutes}</strong><span>分鐘</span></div></div><button className="primary" onClick={()=>{setRun(null);setCorrect(0);setScreen("home")}}>回到首頁</button></main>;
 if(!exercise||!run)return null;const chunks=exercise.type==="chunk_ordering";
 return <main className="shell"><div className="lesson-head"><div><p className="eyebrow">請對方進一步說明</p><strong>{index+1} / {run.exercises.length}</strong></div><button aria-label="返回首頁" onClick={()=>setScreen("home")}>關閉</button></div><div className="progress" aria-label="課程進度"><div style={{width:`${(index+1)/run.exercises.length*100}%`}}/></div><section className="card"><h1 style={{fontSize:25}}>{exercise.prompt}</h1>{exercise.content.context&&<p className="context">{exercise.content.context}</p>}{exercise.type==="listening_choice"&&<div className="audio"><button onClick={speak} aria-label="播放英文">▶</button><div><strong>播放英文</strong><br/><small>0.85× · 可重複播放</small></div></div>}{chunks&&<div className="answer-line">{selected.map(id=>optionMap.get(id)).join(" ")||"依序點選句塊…"}</div>}<div className={chunks?"chunks":"options"}>{exercise.content.options?.map(o=><button key={o.id} className={`${chunks?"chunk":"option"}${selected.includes(o.id)?" selected":""}`} onClick={()=>choose(o.id)} disabled={Boolean(feedback)}>{o.text}</button>)}</div>{feedback&&<div className={`feedback ${feedback.isCorrect?"correct":"wrong"}`} role="status"><strong>{feedback.isCorrect?"答對了":"再記一次"}</strong><div>{feedback.message}</div>{!feedback.isCorrect&&<div>正確答案：{feedback.correctIds.map(id=>optionMap.get(id)??id).join(" ")}</div>}</div>}{error&&<p className="error" role="alert">{error}</p>}{!feedback?<button className="primary" onClick={submit} disabled={busy||!selected.length}>{busy?"送出中…":"確認答案"}</button>:<button className="primary" onClick={next} disabled={busy}>{index===run.exercises.length-1?"完成短課":"下一題"}</button>}</section></main>;
}
