"use client";
import { useEffect,useMemo,useState } from "react";
import { AudioPlayer } from "./audio-player";
type Option={id:string;text:string};type Asset={id:string;status:string;url:string|null;voice:string|null;durationMs:number|null};type Exercise={id:string;position:number;type:string;prompt:string;content:{context?:string;speech?:string;options?:Option[];audio?:Asset}};type Run={id:string;currentPosition:number;status:string;exercises:Exercise[]};type Feedback={isCorrect:boolean;correctIds:string[];message:string};type Progress={completedUnits:number;inProgressUnits:number;mastery:Array<{dimension:string;intervalDays:number}>};
export function LearningApp(){
 const[screen,setScreen]=useState<"home"|"lesson"|"done">("home");const[minutes,setMinutes]=useState(5);const[mode,setMode]=useState("一般");const[run,setRun]=useState<Run|null>(null);const[index,setIndex]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[feedback,setFeedback]=useState<Feedback|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[correct,setCorrect]=useState(0);const[progress,setProgress]=useState<Progress|null>(null);const exercise=run?.exercises[index];const optionMap=useMemo(()=>new Map(exercise?.content.options?.map(option=>[option.id,option.text])??[]),[exercise]);
 async function start(){setBusy(true);setError("");try{const created=await fetch("/api/unit-runs",{method:"POST"});if(!created.ok)throw new Error("目前無法開始課程，請確認資料庫已啟動。");const{id}=await created.json();const response=await fetch(`/api/unit-runs/${id}`);if(!response.ok)throw new Error("無法載入課程內容。");const data:Run=await response.json();setRun(data);setIndex(Math.min(Math.max(data.currentPosition,0),Math.max(data.exercises.length-1,0)));setSelected([]);setFeedback(null);setScreen("lesson")}catch(cause){setError(cause instanceof Error?cause.message:"發生未預期錯誤。")}finally{setBusy(false)}}
 function choose(id:string){if(feedback)return;if(exercise?.type==="chunk_ordering")setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]);else setSelected([id])}
 async function submit(){if(!run||!exercise||!selected.length)return;setBusy(true);setError("");try{const response=await fetch("/api/exercise-attempts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({unitRunId:run.id,exerciseId:exercise.id,clientEventId:crypto.randomUUID(),selectedIds:selected,displayOrder:exercise.content.options?.map(option=>option.id)??[]})});if(!response.ok)throw new Error("答案送出失敗，請再試一次。");const result:Feedback=await response.json();setFeedback(result);if(result.isCorrect)setCorrect(value=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:"答案送出失敗。")}finally{setBusy(false)}}
 async function next(){if(!run||!feedback)return;if(index<run.exercises.length-1){setIndex(value=>value+1);setSelected([]);setFeedback(null);return}setBusy(true);const response=await fetch(`/api/unit-runs/${run.id}/complete`,{method:"POST"});setBusy(false);if(response.ok){setScreen("done");fetch("/api/progress").then(result=>result.ok?result.json():null).then(setProgress).catch(()=>null)}else setError("課程完成狀態未能儲存，請再試一次。")}
 useEffect(()=>{fetch("/api/progress").then(response=>response.ok?response.json():null).then(setProgress).catch(()=>null);return()=>{if("speechSynthesis"in window)window.speechSynthesis.cancel()}},[]);
 if(screen==="home")return <main className="shell"><header className="brand"><strong>LaLea</strong><span>Language Learning</span></header><p className="eyebrow">今天的小步前進</p><h1>用零散時間，練出能開口的職場英文。</h1><p className="lead">先從一般商務溝通開始。每堂短課會混合單字、片語、聽力和實際對話。</p>{progress&&<section className="card" aria-label="學習進度"><span className="label">你的學習進度</span><div className="stats"><div className="stat"><strong>{progress.completedUnits}</strong><span>完成短課</span></div><div className="stat"><strong>{progress.inProgressUnits}</strong><span>進行中</span></div><div className="stat"><strong>{progress.mastery.length}</strong><span>掌握面向</span></div></div></section>}<section className="card"><span className="label">現在有多少時間？</span><div className="pills">{[3,5,10].map(value=><button className="pill" aria-pressed={minutes===value} onClick={()=>setMinutes(value)} key={value}>{value} 分鐘</button>)}</div></section><section className="card"><span className="label">目前的環境</span><div className="pills">{["一般","安靜","純聽"].map(value=><button className="pill" aria-pressed={mode===value} onClick={()=>setMode(value)} key={value}>{value}</button>)}</div></section>{error&&<p className="error" role="alert">{error}</p>}<button className="primary resume" onClick={start} disabled={busy}>{busy?"準備課程中…":`繼續學習 · ${minutes} 分鐘`}</button></main>;
 if(screen==="done")return <main className="shell finish"><div className="mark">✓</div><p className="eyebrow">今日短課完成</p><h1>做得好，這些句子已加入你的學習進度。</h1><div className="stats"><div className="stat"><strong>{correct}/{run?.exercises.length}</strong><span>答對</span></div><div className="stat"><strong>3</strong><span>片語</span></div><div className="stat"><strong>約 {minutes}</strong><span>分鐘</span></div></div><button className="primary" onClick={()=>{setRun(null);setCorrect(0);setScreen("home")}}>回到首頁</button></main>;
 if(!exercise||!run)return null;const chunks=exercise.type==="chunk_ordering";
 return <main className="shell"><div className="lesson-head"><div><p className="eyebrow">一般商務英語</p><strong>{index+1} / {run.exercises.length}</strong></div><button aria-label="返回首頁" onClick={()=>setScreen("home")}>關閉</button></div><div className="progress" aria-label="課程進度"><div style={{width:`${(index+1)/run.exercises.length*100}%`}}/></div><section className="card"><h1 style={{fontSize:25}}>{exercise.prompt}</h1>{exercise.content.context&&<p className="context">{exercise.content.context}</p>}{exercise.type==="listening_choice"&&exercise.content.speech&&<AudioPlayer exerciseId={exercise.id} text={exercise.content.speech} asset={exercise.content.audio}/>} {chunks&&<div className="answer-line">{selected.map(id=>optionMap.get(id)).join(" ")||"依序點選句塊…"}</div>}<div className={chunks?"chunks":"options"}>{exercise.content.options?.map(option=><button key={option.id} className={`${chunks?"chunk":"option"}${selected.includes(option.id)?" selected":""}`} onClick={()=>choose(option.id)} disabled={Boolean(feedback)}>{option.text}</button>)}</div>{feedback&&<div className={`feedback ${feedback.isCorrect?"correct":"wrong"}`} role="status"><strong>{feedback.isCorrect?"答對了":"再記一次"}</strong><div>{feedback.message}</div>{!feedback.isCorrect&&<div>正確答案：{feedback.correctIds.map(id=>optionMap.get(id)??id).join(" ")}</div>}</div>}{error&&<p className="error" role="alert">{error}</p>}{!feedback?<button className="primary" onClick={submit} disabled={busy||!selected.length}>{busy?"送出中…":"確認答案"}</button>:<button className="primary" onClick={next} disabled={busy}>{index===run.exercises.length-1?"完成短課":"下一題"}</button>}</section></main>
}
