"use client";
import { useEffect,useState } from "react";
import { randomUUID } from "@/lib/client-id";
type Due={userVocabularyId:string;form:string;partOfSpeech:string|null;translation:string|null;example:string|null;exampleTranslation:string|null;dimension:"reading_recognition"|"listening_recognition"|"active_recall";nextReviewAt:string};type Fresh={userVocabularyId:string;form:string;partOfSpeech:string|null;translation:string|null;example:string|null;exampleTranslation:string|null};type Queue={due:Due[];new:Fresh[];policy:{newAllowance:number;dueCount:number}};
const labels={reading_recognition:"閱讀辨識",listening_recognition:"聽力辨識",active_recall:"主動提取"};
export function ReviewPanel(){const[queue,setQueue]=useState<Queue|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);async function load(){const response=await fetch("/api/reviews/queue");if(response.ok)setQueue(await response.json())}useEffect(()=>{let active=true;fetch("/api/reviews/queue").then(r=>r.ok?r.json():null).then(result=>{if(active)setQueue(result)}).catch(()=>null);return()=>{active=false}},[]);
 const dueItem=queue?.due[0];const freshItem=!dueItem?queue?.new[0]:undefined;const isFirstLearning=!dueItem&&Boolean(freshItem);
 const item:Due|undefined=dueItem??(freshItem?{...freshItem,dimension:"reading_recognition",nextReviewAt:""}:undefined);
 function speak(){if(!item||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(item.form);utterance.lang="en-US";window.speechSynthesis.speak(utterance)}
 async function rate(rating:"forgot"|"hard"|"mastered"|"too_easy"){if(!item)return;setBusy(true);const response=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userVocabularyId:item.userVocabularyId,dimension:item.dimension,clientEventId:randomUUID(),isCorrect:rating!=="forgot",rating})});const result=await response.json();setBusy(false);if(response.ok){setMessage(`已安排下次複習：${result.reason}`);await load()}}
 return <main className="shell"><p className="eyebrow">到期複習</p><h1>先處理需要回想的內容。</h1><p className="lead">閱讀、聽力與主動提取分開安排；新的詞彙只會填入剩餘量。</p>{!queue?<section className="card">載入中…</section>:item?<section className="card"><span className="label">{isFirstLearning?`首次學習 · 可學 ${queue.new.length}`:`${labels[item.dimension]} · 剩餘 ${queue.due.length}`}</span><div style={{display:"flex",alignItems:"center",gap:10}}><h1 style={{fontSize:30,margin:0}}>{item.form}</h1>{item.partOfSpeech&&<span className="context" style={{margin:0,padding:"3px 10px"}}>{item.partOfSpeech}</span>}<button aria-label="播放發音" onClick={speak} style={{border:0,borderRadius:"50%",width:36,height:36,background:"var(--mint)",color:"var(--ink)",cursor:"pointer"}}>🔊</button></div><p className="context">{item.translation??"回想這個詞義與使用情境"}</p>{item.example&&<p className="context"><strong>{item.example}</strong>{item.exampleTranslation&&<><br/><span>{item.exampleTranslation}</span></>}</p>}<span className="label">{isFirstLearning?"第一次看到，先試著回想意思：":"這次回想得如何？"}</span><div className="review-ratings"><button disabled={busy} onClick={()=>rate("forgot")}>忘記</button><button disabled={busy} onClick={()=>rate("hard")}>困難</button><button disabled={busy} onClick={()=>rate("mastered")}>掌握</button><button disabled={busy} onClick={()=>rate("too_easy")}>太容易</button></div>{message&&<p className="context" role="status">{message}</p>}</section>:<section className="card"><h2>目前沒有到期項目</h2><p className="lead">可開始的新詞：{queue.new.length} 個；今日允許新增上限：{queue.policy.newAllowance} 個。</p></section>}</main>}
